### ISSUE TITLE
How to add time delay to the profile

### ISSUE THREAD

**Issue by Zhengjle1** [hightower8083/axiprop#23]
I want to know how to add time delay which is used to control the velocity of the laser profile?

**Comment by hightower8083** [comment]
hi @Zhengjle1 

sorry, but the question is not very clear.. the field in axiprop is natively defined in the spectral domain, and when we create or edit the pulse we rather operate its phase, for example when we want to add focusing with a parabolic mirror we multiply it with a phase which depends quadratically on the radius
https://github.com/hightower8083/axiprop/blob/96c3cb293b5a24ad2c234556d24806c3d09444f6/axiprop/utils.py#L166

In order to control the group velocity of the laser you need to add more then delay but also a linear chirp with a pulse front curvature as e.g. in [https://doi.org/10.1364/OPTICA.4.001298]. There are other ways to do that with axiparabolas [https://doi.org/10.1088/2040-8986/ac57d2] or other fancy optics.

Let me know if this is helpful and if not you'll have to provide more details on your goal.

**Comment by Zhengjle1** [comment]
Hi @hightower8083 
Thanks for attention and sorry for the inaccurate explanation!! I want to add the radial delay which is the expression in this article[https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.124.134802]. I understand that the axiparabola's role in your code is providing an extra phase to the incident laser and your code calculates the final optic distribution in the place interested, but I don't know how to add the radial delay in your code.

**Comment by hightower8083** [comment]
dear @Zhengjle1 

I know this paper but I haven't tried modeling this paritcular echelon optics.  As far as I know in order to control the group velocity and acceleration, you may play with 2nd and 4th order STCs, and here is an example of the implmentations:
```python
def mirror_axiparabola(kz, r, f0, d0, R ):
    # frequncy 2D array of proper shape
    kz2d = ( kz * np.ones((*kz.shape, *r.shape)).T ).T
    # sag profile from [Smartsev et al]
    s_ax = r**2/4/f0 - d0/(8*f0**2*R**2)*r**4 \
         + d0*(R**2+8*f0*d0)/(96*f0**4*R**4)*r**6
    # phase to add
    phi = -2 * s_ax[None,:] * kz2d
    return np.exp(1j * phi)

def add_STC2(kz, r, alfa_PFC, k0, R_las):    
    kz2d = ( kz * np.ones((*kz.shape, *r.shape)).T ).T
    phi = -alfa_PFC * (kz2d-k0) * c * (r/R_las)**2
    return np.exp(1j * phi)

def add_STC4(kz, r, alfa_PFC4, k0, R_las):    
    kz2d = ( kz * np.ones((*kz.shape, *r.shape)).T ).T
    phi = -alfa_PFC4 * (kz2d-k0) * c * (r/R_las)**4
    return np.exp(1j * phi)

# applying to existing initial field
E0 *= mirror_axiparabola(prop.kz, prop.r, f0, d0, R_mirr )
E0 *= add_STC4(prop.kz, prop.r, alfa_PFC4)
E0 *= add_STC2(prop.kz, prop.r, alfa_PFC)
```
where `alfa_PFC` and `alfa_PFC4` should typically be of the order of tens of femtosecons (negative or positive). Using these two parameters with some reasonable mirror design, i could get axiparabola beam going at `c` without acceleration:
![image](https://github.com/hightower8083/axiprop/assets/22051570/6fdc1a95-9c04-4972-9592-e8dbc1a87a2c)

Let me know if this is helpful or if you have more questions

**Comment by Zhengjle1** [comment]
Thanks for answering my questions!@hightower8083
In my understanding of your code, the STC2 and STC4 applied to the code is the time delay determined by the formula(19) in this paper(https://iopscience.iop.org/article/10.1088/2040-8986/ac57d2). And in order to add the time delay in the spectral domain, you play a Fourier transform in the time domain(which in your code I think it's equal to operate in the kz domain by multiple 'c').
In this paper(https://opg.optica.org/optica/fulltext.cfm?uri=optica-4-10-1298&id=375276), the time delay is calculated in the ω domain and is associated with 'r' in the form of this(which is just like the expression in your code):
![d9a8ff15f91f9623f905260248fa93e](https://github.com/hightower8083/axiprop/assets/162555291/b5c7941a-0805-4fe9-ab77-6a82325981ba)
Please let me know whether my understanding is right or point out my mistakes.

**Comment by hightower8083** [comment]
hi @Zhengjle1 

I think your understanding is correct. Here is another specifying example of the axiprop workflow.
Usually we conveniently create the initial field with a envelope container class:
```python 
# define some laser parameters
R_las = ...         # initial laser size in meters
tau = ...                # initial laser duration in seconds
LaserEnergy = ...   # total laser energy in Joules
lambda0 = ...      # laser central wavelength


# numerical parameters
R_1 = ...         # size of the screen needed for studies after propagation 
Nt = ...            # number of sample points in time (for the envelope)
Nr0 =  ...         # number of sample points in radial direction (for initial field at mirrro)
Nr1 =  ...          # number of sample points in radial direction (for final, focused field)

# 
k0 = 2 * np.pi / lambda0
t_axis = np.linspace(-4*tau, 4*tau, Nt)
r_axis = np.linspace(0, 4*R_las, Nr0)
r_axis_new = np.linspace(0, R_1, Nr1)
k_axis = ScalarFieldEnvelope(k0, t_axis).k_freq


# Make Gaussian laser object
LaserObject = ScalarFieldEnvelope( k0, t_axis )
LaserObject.make_gaussian_pulse(r_axis, tau, R_las, Energy=LaserEnergy, n_ord=2)

E0 = LaserObject.Field_ft.copy()
```
At the point we have the complex envelop field which is a 2D array of the shape `(Nt, Nr)` (note that Nt corresponds to a number of frequency components which is equal to time points due to FFT). 

You can manipulate it by adding the frequency and spatially-dependent phase, e.g. 
```python
E0 *= mirror_axiparabola(k_axis, r_axis, f0, d0, R_mirr )
```

The expression that you have posted is indeed equivalent to the `add_STC2` function from my previous post.
